- prance/util/resolver.py
the simplest big fix for speed i refer to in #11
> dedup changes list for speed

- tests/specs/issue_39.yaml
- tests/test_resolving_parser.py
> Add test case for PR #39

- changelog.d/51.bugfix
- prance/__init__.py
- prance/cli.py
- prance/util/__init__.py
- prance/util/fs.py
- prance/util/resolver.py
- prance/util/url.py
- tests/specs/issue_51/openapi-main.yaml
- tests/specs/issue_51/openapi-part-iso-8859-2.yaml
- tests/specs/issue_51/openapi-part.yaml
- tests/test_resolving_parser.py
- tests/test_util_fs.py
Fixes #51 .
- Allow forcing the encoding of *local* (i.e. `file://` and `python://` URLs)
- Add CLI parameter for this
@jfinkhaeuser
> Add test case for issue #51

- prance/__init__.py
- prance/util/__init__.py
- prance/util/exceptions.py
- prance/util/fs.py
- prance/util/iterators.py
- prance/util/path.py
- prance/util/resolver.py
- tests/__init__.py
- tests/test_util_fs.py
- tests/test_util_url.py
Improves test coverage
@jfinkhaeuser
> Improves test coverage

- changelog.d/53.misc
- prance/util/path.py
> Improve coverage

- changelog.d/55.feature
- prance/__init__.py
> 55 none value at recursion limit

- changelog.d/36.feature
- prance/__init__.py
- prance/util/exceptions.py
- tests/specs/issue_36.yaml
- tests/test_backends.py
> Improve error reporting

- README.rst
- changelog.d/23.feature
- prance/__init__.py
- prance/util/resolver.py
- tests/test_util_resolver.py
> Implement partial resolution

- prance/util/resolver.py
- tests/test_resolving_parser.py
- tests/test_util_resolver.py
Fixes #65 .
- Enforce comparison of parsed URLs to parsed URLs; the raw resolver may be using strings.
@jfinkhaeuser
> Issue 65 partial resolution error

- prance/util/url.py
- tests/test_util_resolver.py
Fixes #69 .
- Catch `urllib.parse()` errors and re-raise them with context.
@jfinkhaeuser
> Test case and fix for #69

- prance/util/url.py
- tests/test_base_parser.py
- tests/test_util_resolver.py
> Transform FileNotFoundError to ResolutionError in fetch_url

- prance/util/formats.py
- Fix a type hinting in prance/util/formats.py
@jfinkhaeuser
> Fix type hinting

- README.rst
Fixes #91.
- Remove mention that the project is up for adoption in the README.
> Remove mention that the project is up for adoption

- README.rst
> Fixed documentation url

- prance/util/translator.py
@RonnyPfannschmidt I didn’t push this commit into #101, where you requested this change to the header. Sorry for the trouble.
> 📝 Fix translator author

- prance/__init__.py
- setup.cfg
Fixes #131
- refactor imports to latest release https://github.com/p1c2u/openapi-spec-validator/releases/tag/0.5.0
> refactor openapi_spec_validator imports

- .github/workflows/pythonpackage.yml
- tox.ini
* drop py36
* align tox.ini
* run ci on pr
> fix builds

- prance/__init__.py
- setup.cfg
Fixes #127.
- deprecated distutils.version changed to packaging.version
> Change deprecated distutils.version to packaging.version

- CHANGES.rst
this prepares the next release and fixes #148
> Update CHANGES.rst and prepare release

- CHANGES.rst
- pyproject.toml
- setup.cfg
* fix changelog
* update setuptools metadata
this prepares the next release
> prepare release 2025.04.08.0
